#! /usr/bin/env bash

set -euo pipefail

config_name="southern_africa128_fullres_pr_cmip_cncsnpp_continuous"
vtag="t128_all-no-hum"
train_dataset="step2_comb_${vtag}"
hadgem3_dataset="henry_comb_hadgem3_${vtag}" 
gcm_dataset="henry_comb_${vtag}"
sde="subvpsde"
workdir="output/test/${sde}/${config_name}/${train_dataset}/test-run"
config_path="src/ml_downscaling_emulator/score_sde_pytorch/configs/${sde}/${config_name}.py"

loc_spec_channels=0
epoch=300


num_samples=1
eval_batchsize=32
checkpoint="epoch_${epoch}"

#rm -rf "${workdir}/samples/${checkpoint}/${dataset}"
#for member in 42 77 174 272
#do
#    python bin/predict.py ${workdir} --dataset ${gcm_dataset} --checkpoint ${checkpoint} --batch-size ${eval_batchsize} --num-samples ${num_samples} --ensemble-member ${member} --split test --input-transform-dataset=${train_dataset}  --input-transform-key=pixelmmsstan
#done


python bin/predict.py ${workdir} --dataset ${hadgem3_dataset}  --checkpoint ${checkpoint} --batch-size ${eval_batchsize} --num-samples ${num_samples} --ensemble-member 129 --split test --input-transform-dataset=${train_dataset} --input-transform-key=pixelmmsstan


